shader_type spatial;
uniform float height = 64;
uniform sampler2D color_gradiant;
uniform sampler2D normal_map;

void fragment() {
	vec4 world_matrix = INV_VIEW_MATRIX * vec4(VERTEX,1.0);
	vec3 model_vertex = (inverse(MODEL_MATRIX)*world_matrix).xyz;
	float gradiant_uv = (model_vertex.y/height) + 0.5;
	ALBEDO = texture(color_gradiant,vec2(gradiant_uv)).rgb;
	NORMAL_MAP = texture(normal_map,UV).xyz;
}

